name: Reusable Echo Workflow

on:
  workflow_call:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Hello from reusable workflow ðŸ‘‹"

      - name: Step 2
        run: echo "This workflow is shared across repositories"

      - name: Step 3
        run: echo "No Java, no Maven, no duplication"
