name: Reusable Workflow

on:
  workflow_call:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Echo job"

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build job"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test job"
